### ISSUE TITLE
Conda forge recipe

### ISSUE THREAD

**Issue by ashiklom** [nasa/harmony-py#48]
It would be great to have a conda-forge recipe for Harmony, to facilitate installation and version management via conda.

[Here are the docs for adding recipes to conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html). I played around with this briefly and it is very straightforward to create recipes from pip using grayskull; it took me about 3 minutes to produce the recipe file below.

Once the recipe is created, I think all you have to do is submit a PR to https://github.com/conda-forge/staged-recipes.

Since it doesn't seem like much work, I can do this myself and implicitly volunteer as a maintainer of the recipe. However, I thought I'd post on here first to see if there were any reasons not to do this and/or if someone internal to ESDIS would step up to maintain the recipe instead.

<details>

<summary>Example recipe file</summary>

```yaml
{% set name = "harmony-py" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harmony-py-{{ version }}.tar.gz
  sha256: 69ac699973c8dc430780cb6a2169a072eeffec7e11be4e6d0b4da8755b086d8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - curlify >=2.2,==2.*
    - progressbar2 >=3.5,==3.*
    - python >=3.6,<4.0
    - python-dateutil >=2.7.5,==2.7.*
    - python-dotenv >=0.1,==0.*
    - requests >=2.2,==2.*
    - sphinxcontrib-napoleon >=0.7

test:
  imports:
    - harmony_py
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nasa/harmony-py
  summary: The NASA Harmony Python library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ashiklom
```

</details>
